[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.7"
bevy_spicy_networking = { git = "https://github.com/schmidtadrian/bevy_spicy_networking.git", branch = "master" }
serde = { version = "1.0.125", features = ["derive"] }
typetag = "0.2.0"